<?php
include_once ("sesio.phtml");
?>
<!DOCTYPE HTML>
<html lang="es">
    <head>
        <?php include_once ("componentesHead.phtml");?>
    </head>
    <body>
        <?php include_once ("cabeceraDePagina.phtml");?>
        <section id="pagina" class="container">
            <?php include_once ("formularioNosotros.phtml");?>
        </section>
        <?php include_once ("pieDePagina.phtml");?>
        <?php include_once ("scripts.phtml");?>
    </body>
</html>