<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">
<title>UMSS | Laboratorio de Geotecnia</title>
<link href="<?php echo Conexion::ruta();?>css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo Conexion::ruta();?>css/font-awesome.min.css" rel="stylesheet">
<link href="<?php echo Conexion::ruta();?>css/prettyPhoto.css" rel="stylesheet">
<link href="<?php echo Conexion::ruta();?>css/animate.css" rel="stylesheet">
<link href="<?php echo Conexion::ruta();?>css/main.css" rel="stylesheet">
<link rel="shortcut icon" href="<?php echo Conexion::ruta();?>images/ico/favicon.ico">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="<?php echo Conexion::ruta();?>images/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="<?php echo Conexion::ruta();?>images/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="<?php echo Conexion::ruta();?>images/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="<?php echo Conexion::ruta();?>images/ico/apple-touch-icon-57-precomposed.png">
<?php if(isset ($_SESSION['idUsuario'])) {?>
    <?php if ($_SESSION['codRol'] == 2) {?>
        <link href="<?php echo Conexion::ruta();?>calendario/fullcalendar.css" rel="stylesheet">
        <link href="<?php echo Conexion::ruta();?>calendario/fullcalendar.print.css" rel="stylesheet" media="print">
        <script src="<?php echo Conexion::ruta();?>calendario/lib/moment.min.js"></script>
        <script src="<?php echo Conexion::ruta();?>calendario/lib/jquery.min.js"></script>
        <script src="<?php echo Conexion::ruta();?>calendario/lib/jquery-ui.custom.min.js"></script>
        <script src="<?php echo Conexion::ruta();?>calendario/fullcalendar.min.js"></script>
    <?php }?>
<?php }?>
