<!DOCTYPE HTML>
<html lang="es">
    <head>
        <?php include_once ("componentesHead.phtml");?>
    </head>
    <body>
        <?php include_once ("cabeceraDePagina.phtml");?>
        <section id="error" class="container">
            <h1>404, Pagina no encontrada</h1>
            <p>La pagina que estas buscando no existe.</p>
            <a class="btn btn-success" href="<?php echo Conexion::ruta();?>">VOLVER AL INICIO</a>
        </section>
        <?php include_once ("pieDePagina.phtml");?>
    </body>
</html>  