<div id="admin_wrapper">
    <form action="" method="post" name="formPagoTodoProyecto">
        <div class="form-group">
            <label>Proyecto:</label>
            <select class="form-control" name="proyectoT">
                <?php for ($i = 0; $i < sizeof($listaProyectoELSinPago); $i = $i + 7) {?>
                    <option value="<?php echo $listaProyectoELSinPago[$i]; ?>">
                        <?php echo $listaProyectoELSinPago[$i + 2].' - '.$listaProyectoELSinPago[$i + 1]; ?>
                    </option>
                <?php } ?>
                <?php for ($i = 0; $i < sizeof($listaProyectoTCSinPago); $i = $i + 7) {?>
                    <option value="<?php echo $listaProyectoTCSinPago[$i]; ?>">
                        <?php echo $listaProyectoTCSinPago[$i + 2].' - '.$listaProyectoTCSinPago[$i + 1]; ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <p>
            <input type="hidden" name="grabarPagoTodoProyecto" value="si" />
            <input type="button" value="Aceptar"  class="btn btn-default" onclick="document.formPagoTodoProyecto.submit();"/>
        </p>
    </form>
</div>