<div id="admin_wrapper">
    <form action="" method="post" name="formD">
        <div class="form-group">
            <select class="form-control"  name="reporte">
                <option value="solicitud">Solicitud</option>
                <option value="ensayoLaboratorio">Ensayo de laboratorio</option>
                <option value="muestra">Muestra</option>
                <option value="trabajoCampo">Trabajo de campo</option>
            </select>
        </div>
        <div class="form-group">
            <select class="form-control" name="anio">
                <option value="todo">Todos</option>
                <option value="<?php echo date("Y"); ?>"><?php echo date("Y"); ?></option>
                <option value="<?php echo date("Y") - 1; ?>"><?php echo date("Y") - 1; ?></option>
                <option value="<?php echo date("Y") - 2; ?>"><?php echo date("Y") - 2; ?></option>
            </select>
        </div>
        <p>
            <input type="hidden" name="grabar" value="si" />
            <input type="button" value="Imprimir"  class="btn btn-default" onclick="document.formD.submit();"/>
        </p>
    </form>
</div>