<h2>Informes finales cargados:</h2>
<?php include_once ('tablaInformeFinal.phtml');?>
<h2>Formulario para subir resultados:</h2>
<div id="admin_wrapper">
    <form action="" method="post" name="formSubirResultadoTC">
        <div class="form-group">
            <input type="text" class="form-control" name="idSolicitud" value="<?php echo $idSolicitud; ?>" disabled/>
        </div>
        <div class="form-group">
            <label>Archivo:</label>
            <input type = "file" class = "form-control" name = "archivo" required=""/>
        </div>
        <div class="form-group">
            <label>Descripcion:</label>
            <textarea class="form-control" rows="3" name="descripcion"></textarea>
        </div>
        <p>
            <input type="hidden" name="grabarSubirResultadoTC" value="si" />
            <input type="button" value="Ingresar"  class="btn btn-default" onclick="document.formSubirResultadoTC.submit();"/>
        </p>
    </form>
</div>