<div id="admin_wrapper">
    <form action="" method="post" name="formResultadoTC">
        <div class="form-group">
            <label>Proyecto:</label>
            <select class="form-control" name="proyectoTC">
                <?php for ($i = 0; $i < sizeof($listaProyectoTCHabilitado); $i = $i + 7) {?>
                    <option value="<?php echo $listaProyectoTCHabilitado[$i]; ?>">
                        <?php echo $listaProyectoTCHabilitado[$i + 2].' - '.$listaProyectoTCHabilitado[$i + 1]; ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <p>
            <input type="hidden" name="grabarResultadoTC" value="si" />
            <input type="button" value="Aceptar" class="btn btn-default" onclick="document.formResultadoTC.submit();"/>
        </p>
    </form>
</div>