<h2>Formulario de registro un ensayo de tipo suelo:</h2>
<div id="admin_wrapper">
    <form action="" method="post" name="formRegistroSuelo">
        <div class="form-group">
            <input type="text" class="form-control" name="idEnsayoLaboratorio" value="<?php echo $idEnsayoSolicitud; ?>" disabled/>
        </div>
        <label>Parametros de deformación en condición no drenada:</label>
        <div class="table-responsive">
            <table>
                <thead>
                <tr>
                    <th width="35%"></th>
                    <th width="20%"></th>
                    <th width="45%"></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS25">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS25">[LS25]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Corte directo</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS25a">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS25a">[LS25a]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Corte directo con partículas de sobre tamaño</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS26">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS26">[LS26]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Triaxial CD</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS27">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS27">[LS27]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Triaxial CU</h5>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <label>Suelos no saturados:</label>
        <div class="table-responsive">
            <table>
                <thead>
                <tr>
                    <th width="35%"></th>
                    <th width="20%"></th>
                    <th width="45%"></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS31">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS31">[LS31]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Papel filtro</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS32">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS32">[LS32]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Placa de presion</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS33">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS33">[LS33]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Triaxial modificado</h5>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <label>Suelos especiales:</label>
        <div class="table-responsive">
            <table>
                <thead>
                <tr>
                    <th width="35%"></th>
                    <th width="20%"></th>
                    <th width="45%"></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS34">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS34">[LS34]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Erosion interna</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS35">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS35">[LS35]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Ensayo químico de fracciones de suelo</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS36">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS36">[LS36]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Doble hidrometria</h5>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <label>Resistencia de agregados:</label>
        <div class="table-responsive">
            <table>
                <thead>
                <tr>
                    <th width="35%"></th>
                    <th width="20%"></th>
                    <th width="45%"></th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS37">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS37">[LS37]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Abrasion de los angeles agregados</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS38">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS38">[LS38]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Ensayo de sulfato de sodio en agregados	</h5>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="form-group">
                            <select class="form-control" name="cantidadLS39">
                                <?php for ($i = 1; $i <= 50; $i++) {?>
                                    <option class="form-group" value="<?php  echo $i; ?>"><?php  echo $i; ?></option>
                                <?php }?>
                            </select>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="LS39">[LS39]
                            </label>
                        </div>
                    </td>
                    <td>
                        <h5>Ensayo de relacion CBR</h5>
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <p>
            <input type="hidden" name="grabarRegistroSuelo" value="si" />
            <input type="button" value="Registrar suelo"  class="btn btn-default" onclick="document.formRegistroSuelo.submit();"/>
        </p>
    </form>
</div>