<h2>Iniciar Sesion</h2>
                    
<div id="admin_wrapper">
    <?php
    if (isset($_GET['m'])){
        switch ($_GET['m']){
            case '1':
                ?>
                <div class="alert alert-danger" role="alert"><h5>Campos vacíos, no son validos.<h5></div>
                <?php
                break;
            case '2':
                ?>
                <div class="alert alert-danger" role="alert"><h5>Los datos ingresados no son correctos<h5></div>
                <?php
                break;
            case '3':
                ?>
                <div class="alert alert-success" role="alert"><h5>Ha cerrado su sesión correctamente.</h5></div>
                <?php
                break;
        }
    }
    ?>
    <form action="" method="post" name="form">
        <div class="form-group">
            <label>Nombre de cuenta:</label>
            <input type = "text" class = "form-control" name = "login" placeholder = "Nombre de cuenta"/>
        </div>
        <div class="form-group">
            <label>Contraseña:</label>
            <input type = "password" class = "form-control" name = "passwd" placeholder = "Contraseña"/>
        </div>
        <p>
            <input type="hidden" name="grabar" value="si" />
            <input type="button" value="Ingresar"  class="btn btn-default" onclick="document.form.submit();"/>
        </p>
    </form>
</div>
