<h2>Formulario de registro de muestra (Datos de la muestra):</h2>
<div id="admin_wrapper">
    <form action="" method="post" name="formRegistroMuestra">
        <div class="form-group">
            <input type="hidden" class="form-control" name="idEnsayoLaboratorio" value="<?php echo $idEnsayoSolicitud; ?>"/>
        </div>
        <div class="form-group">
            <label>Tipo de muestra:</label>
            <select class="form-control" name="tipoMuestra">
                <option value="Disturbada">Disturbada</option>
                <option value="No disturbada">No disturbada</option>
            </select>
        </div>
        <div class="form-group">
            <label>Ubicación general:</label>
            <input type = "text" class = "form-control" name = "ubicacionGeneral" placeholder = ""/>
        </div>
        <div class="form-group">
            <label>Ubicación específica:</label>
            <input type = "text" class = "form-control" name = "ubicacionEspecifica" placeholder = ""/>
        </div>
        <div class="form-group">
            <label>Profundidad:</label>
            <div class="input-group">
                <input type="text" class="form-control" name="profundidad" placeholder="">
                <span class="input-group-addon" id="basic-addon2">Decímetros</span>
            </div>
        </div>
        <div class="form-group">
            <label>Fecha de toma de la muestra:</label>
            <input type = "date" class = "form-control" name = "fechaTomaMuestra" placeholder = ""/>
        </div>
        <div class="form-group">
            <label>Método de extracción:</label>
            <select class="form-control" name="metodoExtraccion">
                <option value="Cuchara bipartita">Cuchara bipartita</option>
                <option value="Tubo shelby">Tubo shelby</option>
                <option value="Manual">Manual</option>
                <option value="Mostap">Mostap</option>
                <option value="Extraccion nucleo rocas">Extraccion nucleo rocas</option>
            </select>
        </div>
        <div class="form-group">
            <label>Punto de extracción:</label>
            <input type = "text" class = "form-control" name = "puntoExtraccion" placeholder = ""/>
        </div>
        <div class="form-group">
            <label>Descripción:</label>
            <select class="form-control" name="descripcion">
                <option value="Organico">Organico</option>
                <option value="Arcilla">Arcilla</option>
                <option value="Limo">Limo</option>
                <option value="Grava">Grava</option>
                <option value="Bolones">Bolones</option>
                <option value="Rocas">Rocas</option>
                <option value="Arena">Arena</option>
            </select>
        </div>
        <p>
            <input type="hidden" name="grabarRegistroMuestra" value="si" />
            <input type="button" value="Registrar muestra" class="btn btn-default" onclick="document.formRegistroMuestra.submit();"/>
        </p>
    </form>
</div>