
<div id="admin_wrapper">
    <form action="" method="post" name="formInformeFinal">
        <div class="form-group">
            <label>Proyecto:</label>
            <select class="form-control" name="proyecto">
                <?php for ($i = 0; $i < sizeof($listaSolicitud); $i = $i + 8) {?>
                    <option value="<?php echo $listaSolicitud[$i]; ?>">
                        <?php echo $listaSolicitud[$i + 2].' - '.$listaSolicitud[$i + 1]; ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <p>
            <input type="hidden" name="grabarInformeFinal" value="si" />
            <input type="button" value="Aceptar"  class="btn btn-default" onclick="document.formInformeFinal.submit();"/>
        </p>
    </form>
</div>