<h2>Formulario de registro de pago:</h2>
<div id="admin_wrapper">
    <form action="" method="post" name="formRegistroPago">
        <div class="form-group">
            <input type="hidden" class="form-control" name="idSolicitud" value="<?php echo $idSolicitud; ?>"/>
        </div>
        <div class="form-group">
            <label>Nombre del proyecto:</label><br>
            <label><?php echo $listaDetalleFormulario[0]; ?></label>
        </div>
        <div class="form-group">
            <label>Facturación a nombre de:</label><br>
            <label><?php echo $listaDetalleFormulario[1]; ?></label>
        </div>
        <div class="form-group">
            <label>N° de NIT o N° de CI:</label><br>
            <label><?php echo $listaDetalleFormulario[2]; ?></label>
        </div>
        <div class="form-group">
            <label>Nombre de la persona de contacto:</label><br>
            <label><?php echo $listaDetalleFormulario[3]; ?></label>
        </div>
        <div class="form-group">
            <label>Fecha de la solicitud:</label><br>
            <?php
            $dia = date("d", strtotime($listaDetalleFormulario[4]));
            $mes = date("F", strtotime($listaDetalleFormulario[4]));
            if ($mes == "January") { $mes = "Enero"; }
            if ($mes == "February") { $mes = "Febrero"; }
            if ($mes == "March") { $mes = "Marzo"; }
            if ($mes == "April") { $mes = "Abril"; }
            if ($mes == "May") { $mes = "Mayo"; }
            if ($mes == "June") { $mes = "Junio"; }
            if ($mes == "July") {$mes = "Julio"; }
            if ($mes == "August") { $mes = "Agosto"; }
            if ($mes == "September") { $mes = "Septiembre"; }
            if ($mes == "October") { $mes = "Octubre"; }
            if ($mes == "November") { $mes = "Noviembre"; }
            if ($mes == "December") { $mes = "Diciembre"; }
            $anio = date("Y", strtotime($listaDetalleFormulario[4]));
            ?>
            <label><?php echo $dia . " de " . $mes . ", " . $anio ?></label>
        </div>
        <div class="form-group">
            <label>Costo total del proyecto</label>
            <label><?php echo $listaDetalleFormulario[5]; ?></label>
        </div>
        <div class="form-group">
            <input type="text" class="form-control" name="precioTotal" value="<?php echo $listaDetalleFormulario[5]; ?>" disabled/>
        </div>
        <?php if (10000 >= $listaDetalleFormulario[5] and 'privada' == $listaDetalleFormulario[6] and 'Ensayo de laboratorio' == $listaDetalleFormulario[9]) {?>
            <?php if ( false == $listaDetalleFormulario[7]) {?>
        <div class="form-group">
            <h6>Se trata de una institución privada y el monto a cancelar es menor a 10000 bolivianos. Registrar el pago del 100% del monto total.</h6>
            <label>Nro. de orden de pago - 100%:</label>
            <input type="number" class="form-control" name="numeroAnticipo100" />
        </div>
        <div class="form-group">
            <label>Nro. de factura FCYT - 100%:</label>
            <input type="number" class="form-control" name="facturaAnticipo100" />
        </div>
            <?php } else {?>
                <h4>CANCELADO</h4>
            <?php }?>
        <?php }?>
        <?php if (10000 < $listaDetalleFormulario[5] and 'privada' == $listaDetalleFormulario[6] and 'Ensayo de laboratorio' == $listaDetalleFormulario[9]) {?>
            <?php if ( false == $listaDetalleFormulario[7]) {?>
                <div class="form-group">
                    <h6>Se trata de una institución privada y el monto a cancelar es mayor a 10000 bolivianos. Registrar el pago del 50% de anticipo del monto total.</h6>
                    <label>Nro. de orden de pago - 50% anticipo:</label>
                    <input type="number" class="form-control" name="numeroAnticipo50" />
                </div>
                <div class="form-group">
                    <label>Nro. de factura FCYT - 50%:</label>
                    <input type="number" class="form-control" name="numeroFactura50" />
                </div>
            <?php} elseif (false == $listaDetalleFormulario[8]) {?>
                <div class="form-group">
                    <h6>Se trata de una institución privada y el monto a cancelar es mayor a 10000 bolivianos. Registrar el pago del 50% de saldo del monto total.</h6>
                    <label>Nro. de orden de pago - 50% saldo:</label>
                    <input type="number" class="form-control" name="numeroSaldo50" />
                </div>
                <div class="form-group">
                    <label>Nro. de factura FCYT - 50%:</label>
                    <input type="number" class="form-control" name="facturaSaldo50" />
                </div>
            <?php } else {?>
                <h4>CANCELADO</h4>
            <?php }?>
        <?php }?>
        <?php if (10000 >= $listaDetalleFormulario[5] and 'estatal' == $listaDetalleFormulario[6] and 'Ensayo de laboratorio' == $listaDetalleFormulario[9]) {?>
            <?php if ( false == $listaDetalleFormulario[7]) {?>
                <div class="form-group">
                    <h6>Se trata de una institución estatal y el monto a cancelar es menor a 10000 bolivianos. Registrar el pago del 100% del monto total.</h6>
                    <label>Nro. de orden de pago - 100%:</label>
                    <input type="number" class="form-control" name="numeroAnticipo100" />
                </div>
                <div class="form-group">
                    <label>Nro. de factura FCYT - 100%:</label>
                    <input type="number" class="form-control" name="facturaAnticipo100" />
                </div>
            <?php } else {?>
                <h4>CANCELADO</h4>
            <?php }?>
        <?php }?>
        <?php if (10000 < $listaDetalleFormulario[5] and 'estatal' == $listaDetalleFormulario[6] and 'Ensayo de laboratorio' == $listaDetalleFormulario[9]) {?>
            <?php if ( false == $listaDetalleFormulario[7]) {?>
                <div class="form-group">
                    <h6>Se trata de una institución estatal y el monto a cancelar es mayor a 10000 bolivianos. Registrar el pago del 20% de anticipo del monto total.</h6>
                    <label>Nro. de orden de pago - 20% anticipo:</label>
                    <input type="number" class="form-control" name="numeroAnticipo20" />
                </div>
                <div class="form-group">
                    <label>Nro. de factura FCYT - 20%:</label>
                    <input type="number" class="form-control" name="numeroFactura20" />
                </div>
            <?php} elseif (false == $listaDetalleFormulario[8]) {?>
                <div class="form-group">
                    <h6>Se trata de una institución estatal y el monto a cancelar es mayor a 10000 bolivianos. Registrar el pago del 80% de saldo del monto total.</h6>
                    <label>Nro. de orden de pago - 80% saldo:</label>
                    <input type="number" class="form-control" name="numeroSaldo80" />
                </div>
                <div class="form-group">
                    <label>Nro. de factura FCYT - 20%:</label>
                    <input type="number" class="form-control" name="facturaSaldo20" />
                </div>
            <?php } else {?>
                <h4>CANCELADO</h4>
            <?php }?>
        <?php }?>
        <?php if ('privada' == $listaDetalleFormulario[6] and 'Trabajo de campo' == $listaDetalleFormulario[9]) {?>
            <?php if ( false == $listaDetalleFormulario[7]) {?>
                <div class="form-group">
                    <h6>Se trata de una institución privada y es un estudio geotécnico(trabajo de campo). Registrar el pago del 50% de anticipo del monto total.</h6>
                    <label>Nro. de orden de pago - 50% anticipo:</label>
                    <input type="number" class="form-control" name="numeroAnticipo50" />
                </div>
                <div class="form-group">
                    <label>Nro. de factura FCYT - 50%:</label>
                    <input type="number" class="form-control" name="numeroFactura50" />
                </div>
            <?php} elseif (false == $listaDetalleFormulario[8]) {?>
                <div class="form-group">
                    <h6>Se trata de una institución privada y es un estudio geotécnico(trabajo de campo). Registrar el pago del 50% de saldo del monto total.</h6>
                    <label>Nro. de orden de pago - 50% saldo:</label>
                    <input type="number" class="form-control" name="numeroSaldo50" />
                </div>
                <div class="form-group">
                    <label>Nro. de factura FCYT - 50%:</label>
                    <input type="number" class="form-control" name="facturaSaldo50" />
                </div>
            <?php } else {?>
                <h4>CANCELADO</h4>
            <?php }?>
        <?php }?>
        <?php if ('estatal' == $listaDetalleFormulario[6] and 'Trabajo de campo' == $listaDetalleFormulario[9]) {?>
            <?php if ( false == $listaDetalleFormulario[7]) {?>
                <div class="form-group">
                    <h6>Se trata de una institución estatal y es un estudio geotécnico(trabajo de campo). Registrar el pago del 20% de anticipo del monto total.</h6>
                    <label>Nro. de orden de pago - 20% anticipo:</label>
                    <input type="number" class="form-control" name="numeroAnticipo20" />
                </div>
                <div class="form-group">
                    <label>Nro. de factura FCYT - 20%:</label>
                    <input type="number" class="form-control" name="numeroFactura20" />
                </div>
            <?php} elseif (false == $listaDetalleFormulario[8]) {?>
                <div class="form-group">
                    <h6>Se trata de una institución estatal y es un estudio geotécnico(trabajo de campo). Registrar el pago del 80% de saldo del monto total.</h6>
                    <label>Nro. de orden de pago - 80% saldo:</label>
                    <input type="number" class="form-control" name="numeroSaldo80" />
                </div>
                <div class="form-group">
                    <label>Nro. de factura FCYT - 20%:</label>
                    <input type="number" class="form-control" name="facturaSaldo20" />
                </div>
            <?php } else {?>
                <h4>CANCELADO</h4>
            <?php }?>
        <?php }?>
        <p>
            <input type="hidden" name="grabarRegistroPago" value="si" />
            <input type="button" value="Registrar pago"  class="btn btn-default" onclick="document.formRegistroPago.submit();"/>
        </p>
    </form>
</div>