<?php
require_once ('modulo/ensayo/dao/EnsayoDAO.php');
$ensayoDao = new EnsayoDAO();
?>
<h2>Formulario de registro un ensayo de tipo suelo:</h2>
<div id="admin_wrapper">
    <form action="" method="post" name="formRegistroSuelo">
        <div class="form-group">
            <input type="hidden" class="form-control" name="idEnsayoLaboratorio" value="<?php echo $idEnsayoSolicitud; ?>"/>
        </div>
        <label>Parametros de deformación en condición no drenada:</label>
        <?php
        $ensayos = $ensayoDao->obtenerEnsayosPorCategoria('Param. de resistencia CND');
        ?>
        <div class="table-responsive">
            <table style="max-width: 90%;">
                <thead>
                <tr>
                    <th width="15%">Cantidad</th>
                    <th width="20%">Codigo</th>
                    <th width="60%">Nombre</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($ensayos as $ensayo) {
                    ?>
                    <tr>
                        <td style="padding-right: 3%;">
                            <input type="number" class="form-control" name="cantidad<?php echo $ensayo->getCodigo()?>" min = 1>
                        </td>
                        <td>
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="<?php echo $ensayo->getCodigo()?>">[<?php echo $ensayo->getCodigo()?>]
                            </label>
                        </td>
                        <td>
                            <h5><?php echo $ensayo->getDescripcion()?></h5>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
            </table>
        </div>

        <label>Parametros hidráulicos:</label>
        <?php
        $ensayos = $ensayoDao->obtenerEnsayosPorCategoria('Parametros hidraulicos');
        ?>
        <div class="table-responsive">
            <table style="max-width: 90%;">
                <thead>
                <tr>
                    <th width="15%">Cantidad</th>
                    <th width="20%">Codigo</th>
                    <th width="60%">Nombre</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($ensayos as $ensayo) {
                    ?>
                    <tr>
                        <td style="padding-right: 3%;">
                            <input type="number" class="form-control" name="cantidad<?php echo $ensayo->getCodigo()?>" min = 1>
                        </td>
                        <td>
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="<?php echo $ensayo->getCodigo()?>">[<?php echo $ensayo->getCodigo()?>]
                            </label>
                        </td>
                        <td>
                            <h5><?php echo $ensayo->getDescripcion()?></h5>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
            </table>
        </div>
        <label>Suelos no saturados:</label>
        <?php
        $ensayos = $ensayoDao->obtenerEnsayosPorCategoria('Suelos no saturados');
        ?>
        <div class="table-responsive">
            <table style="max-width: 90%;">
                <thead>
                <tr>
                    <th width="15%">Cantidad</th>
                    <th width="20%">Codigo</th>
                    <th width="60%">Nombre</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($ensayos as $ensayo) {
                    ?>
                    <tr>
                        <td style="padding-right: 3%;">
                            <input type="number" class="form-control" name="cantidad<?php echo $ensayo->getCodigo()?>" min = 1>
                        </td>
                        <td>
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="<?php echo $ensayo->getCodigo()?>">[<?php echo $ensayo->getCodigo()?>]
                            </label>
                        </td>
                        <td>
                            <h5><?php echo $ensayo->getDescripcion()?></h5>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
            </table>
        </div>
        <label>Suelos especiales:</label>
        <?php
        $ensayos = $ensayoDao->obtenerEnsayosPorCategoria('Suelos especiales');
        ?>
        <div class="table-responsive">
            <table style="max-width: 90%;">
                <thead>
                <tr>
                    <th width="15%">Cantidad</th>
                    <th width="20%">Codigo</th>
                    <th width="60%">Nombre</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($ensayos as $ensayo) {
                    ?>
                    <tr>
                        <td style="padding-right: 3%;">
                            <input type="number" class="form-control" name="cantidad<?php echo $ensayo->getCodigo()?>" min = 1>
                        </td>
                        <td>
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="<?php echo $ensayo->getCodigo()?>">[<?php echo $ensayo->getCodigo()?>]
                            </label>
                        </td>
                        <td>
                            <h5><?php echo $ensayo->getDescripcion()?></h5>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
            </table>
        </div>
        <label>Resistencia de agregados:</label>
        <?php
        $ensayos = $ensayoDao->obtenerEnsayosPorCategoria('Resistencia de agregados');
        ?>
        <div class="table-responsive">
            <table style="max-width: 90%;">
                <thead>
                <tr>
                    <th width="15%">Cantidad</th>
                    <th width="20%">Codigo</th>
                    <th width="60%">Nombre</th>
                </tr>
                </thead>
                <tbody>
                <?php
                foreach ($ensayos as $ensayo) {
                    ?>
                    <tr>
                        <td style="padding-right: 3%;">
                            <input type="number" class="form-control" name="cantidad<?php echo $ensayo->getCodigo()?>" min = 1>
                        </td>
                        <td>
                            <label class="checkbox">
                                <input name="ensayo[]" class="form-group" type="checkbox" value="<?php echo $ensayo->getCodigo()?>">[<?php echo $ensayo->getCodigo()?>]
                            </label>
                        </td>
                        <td>
                            <h5><?php echo $ensayo->getDescripcion()?></h5>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
            </table>
        </div>
        <p>
            <input type="hidden" name="grabarRegistroSuelo" value="si" />
            <input type="button" value="Registrar suelo"  class="btn btn-default" onclick="document.formRegistroSuelo.submit();"/>
        </p>
    </form>
</div>