<div id="admin_wrapper">
    <form action="" method="post" name="formRegistro">
        <div class="form-group">
            <label>Proyecto:</label>
            <select class="form-control" name="proyecto">
                <?php for ($i = 0; $i < sizeof($listaProyectoConClientePago); $i = $i + 7) {?>
                    <option value="<?php echo $listaProyectoConClientePago[$i]; ?>">
                        <?php echo $listaProyectoConClientePago[$i + 2].' - '.$listaProyectoConClientePago[$i + 1]; ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <p>
            <input type="hidden" name="grabarRegistro" value="si" />
            <input type="button" value="Ver formulario"  class="btn btn-default" onclick="document.formRegistro.submit();"/>
        </p>
    </form>
</div>