<h2>Informes finales cargados:</h2>
<?php include_once ('tablaInformeFinal.phtml');?>
<h2>Formulario para subir informe final:</h2>
<div id="admin_wrapper">
    <form action="" method="post" name="formSubirInformeFinal">
        <div class="form-group">
            <input type="hidden" class="form-control" name="idSolicitud" value="<?php echo $idSolicitud; ?>"/>
        </div>
        <div class="form-group">
            <label>Archivo:</label>
            <input type = "file" class = "form-control" name = "archivo"/>
        </div>
        <div class="form-group">
            <label>Descripcion:</label>
            <textarea class="form-control" rows="3" name="descripcion"></textarea>
        </div>
        <p>
            <input type="hidden" name="grabarSubirInformeFinal" value="si" />
            <input type="button" value="Cargar informe"  class="btn btn-default" onclick="document.formSubirInformeFinal.submit();"/>
        </p>
    </form>
</div>
