<div id="admin_wrapper">
    <form action="" method="post" name="formDetalleEnsayo">
        <div class="form-group">
            <label>Proyecto:</label>
            <select class="form-control" name="proyectoEL">
                <?php for ($i = 0; $i < sizeof($listaProyectoEL); $i = $i + 7) {?>
                    <option value="<?php echo $listaProyectoEL[$i]; ?>">
                        <?php echo $listaProyectoEL[$i + 2].' - '.$listaProyectoEL[$i + 1]; ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <div class="form-group">
            <label>Tipo de ensayo:</label>
            <select class="form-control" name="tipoEnsayo">
                <option value="Suelo">Suelo</option>
                <option value="Roca">Roca</option>
            </select>
        </div>
        <p>
            <input type="hidden" name="grabarDetalleEnsayo" value="si" />
            <input type="button" value="Aceptar" class="btn btn-default" onclick="document.formDetalleEnsayo.submit();"/>
        </p>
    </form>
</div>