<dl class="dl-horizontal">
    <dt>
        <img src="<?php echo Conexion::ruta();?>images/logo3.jpg" class="img-responsive pull-left" width="100%">
    </dt>
    <dd>
        El Laboratorio de Geotecnia de la Universidad Mayor de San Simón, nació el 19 de
        septiembre de 1996, con el apoyo técnico de la cooperación belga dentro del plan
        de mejoramiento de la educación e investigación en el campo de la geotecnia.
    </dd>
    <dt></dt>
    <dd>
        El Laboratorio de Geotecnia de la Universidad Mayor de San Simón, nació el 19 de
        septiembre de 1996, con el apoyo técnico de la cooperación belga dentro del plan
        de mejoramiento de la educación e investigación en el campo de la geotecnia.
    </dd>
    <dt></dt>
    <dd>
        El Laboratorio de Geotecnia de la Universidad Mayor de San Simón, nació el 19 de
        septiembre de 1996, con el apoyo técnico de la cooperación belga dentro del plan
        de mejoramiento de la educación e investigación en el campo de la geotecnia.
    </dd>
    <dt></dt>
    <dd>
        El Laboratorio de Geotecnia de la Universidad Mayor de San Simón, nació el 19 de
        septiembre de 1996, con el apoyo técnico de la cooperación belga dentro del plan
        de mejoramiento de la educación e investigación en el campo de la geotecnia.
    </dd>
</dl>
