<?php
if(!isset($_SESSION['idUsuario']))
{
    header('Location: '.Conexion::ruta().'?accion=inicio');
} else {
    if ($_SESSION['idRol'] != 3) {
        session_destroy();
        header('Location: '.Conexion::ruta().'?accion=inicio');
    }
}
?>
<!DOCTYPE HTML>
<html lang="es">
    <head>
        <?php include_once('componentesHead.phtml');?>
    </head>
    <body onload="document.forms.reset();document.forms.email.focus();">
        <?php include_once ('cabeceraDePagina.phtml');?>
        <section class="container">
            <div class="row">
                <div class="col-md-8">
                    <?php if (false == $formularioRegistroClienteEL and false == $formularioRegistroClienteEG 
                        and false == $formularioRegistroPago and false == $informacionCompletaProyectoEL 
                        and false == $informacionCompletaProyectoTC) {?>
                        <?php include_once ('calendario.phtml'); ?>
                    <?php } if (true == $formularioRegistroClienteEL) {?>
                        <?php include_once ('formularioRegistroClienteEL.phtml'); ?>
                    <?php } ?>
                    <?php if (true == $formularioRegistroClienteEG) {?>
                        <?php include_once ('formularioRegistroClienteEG.phtml'); ?>
                    <?php } ?>
                    <?php if (true == $formularioRegistroPago) {?>
                        <?php include_once ('formularioRegistroPagoProyecto.phtml'); ?>
                    <?php } ?>
                    <?php if (true == $informacionCompletaProyectoEL) {?>
                        <?php include_once ('informacionCompletaProyectoEL.phtml'); ?>
                    <?php } ?>
                    <?php if (true == $informacionCompletaProyectoTC) {?>
                        <?php include_once ('informacionCompletaProyectoTC.phtml'); ?>
                    <?php } ?>
                    <?php include_once ('workflow.phtml'); ?>
                    <?php include_once ('proyecto.phtml'); ?>
                    <?php include_once ('solicitud.phtml'); ?>
                    <?php include_once ('registro.phtml'); ?>
                </div>
                <div class="center gap">
                    <div class="col-md-4" style="margin-top: 10%">
                        <?php include_once ('ultimasDiez.phtml')?>
                    </div>
                </div>
            </div>
        </section>
        <?php include_once ('pieDePagina.phtml');?>
        <?php include_once ('scripts.phtml');?>
    </body>
</html>
