<?php
if(!isset($_SESSION['idUsuario']))
{
    header('Location: '.Conexion::ruta().'?accion=inicio');
} else {
    if ($_SESSION['idRol'] != 5) {
        session_destroy();
        header('Location: '.Conexion::ruta().'?accion=inicio');
    }
}
?>
<!DOCTYPE HTML>
<html lang="es">
    <head>
        <?php include_once('componentesHead.phtml');?>
    </head>
    <body>
        <div id="fb-root"></div>
        <?php include_once ('cabeceraDePagina.phtml');?>
        <section class="container">
            <div class="row">
                <div class="col-md-8">
                    <?php include_once ('calendario.phtml');?>
                    <?php include_once ('workflow.phtml'); ?>
                </div>
                <div class="center gap">
                    <div class="col-md-4">
                        <?php include_once ('ultimasDiez.phtml')?>
                    </div>
                </div>
            </div>
        </section>
        <?php include_once ('pieDePagina.phtml');?>
        <?php include_once ('scripts.phtml');?>
    </body>
</html>
