<?php
include_once ('sesion.phtml');
?>
<!DOCTYPE HTML>
<html lang="es">
    <head>
        <?php include_once ('componentesHead.phtml');?>
    </head>
    <body onload="document.forms.reset();document.forms.email.focus();">
        <?php include_once ('cabeceraDePagina.phtml');?>
        <section class="container">
            <div class="row">
                <div class="center gap">
                    <div class="col-md-8">
                        <?php include_once ('informacionGeotecnia.phtml');?>
                    </div>
                    <div class="col-md-4" style="margin-top: 10%">
                        <?php include_once ('formularioInicioSesion.phtml');?>
                    </div>
                </div>
            </div>
        </section>
        <?php include_once ('pieDePagina.phtml');?>
        <?php include_once ('scripts.phtml');?>
    </body>
</html>
