<footer id="footer" class="midnight-blue">
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                &copy; 2016 <a  href="#" title="WorkFlow para el departamento de Geotecnia">Geotecnia</a>. UMSS.
            </div>
            <div class="col-sm-6">
                <ul class="pull-right">
                    <li><a href="<?php echo Conexion::ruta(); ?>?accion=acercaDeGeotecnia">Acerca de Geotecnia</a></li>
                    <li><a id="gototop" class="gototop" href="#"><i class="icon-chevron-up"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>
