
<div class="modal fade" id="ventanaRegistroDetalleEnsayo" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Proyecto (EL y TC)</h4>
            </div>
            <div class="modal-body">
                <h4>Formulario para el registro de un tipo de ensayo:</h4>
                <?php include_once('formularioRegistroDetalleEnsayo.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaRegistroMuestra" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Proyecto (EL y TC)</h4>
            </div>
            <div class="modal-body">
                <h4>Formulario para el registro de un tipo de ensayo:</h4>
                <?php include_once('formularioRegistroMuestraEL.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaVerDetalleEnsayo" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Proyecto (EL y TC)</h4>
            </div>
            <div class="modal-body">
                <h4>Detalle de ensayos registrados para un determinado proyecto:</h4>
                <?php include_once('tablaDetalleEnsayoProyectoEL.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaRegistroResultadoEL" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Proyecto (EL y TC)</h4>
            </div>
            <div class="modal-body">
                <h4>Formulario para el registro de resultados:</h4>
                <?php include_once('formularioRegistroResultadoEL.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaRegistroAlcance" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Proyecto (EL y TC)</h4>
            </div>
            <div class="modal-body">
                <h4>Formulario para el registro del alcance:</h4>
                <?php include_once('formularioAlcanceTC.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaEditarAlcance" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Proyecto (EL y TC)</h4>
            </div>
            <div class="modal-body">
                <h4>Formulario para la editar un alcance registrado:</h4>
                <?php include_once('formularioEditarAlcanceTC.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaVerAlcance" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Proyecto (EL y TC)</h4>
            </div>
            <div class="modal-body">
                <h4>Formulario para ver un alcance:</h4>
                <?php include_once('formularioVerAlcanceTC.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaRegistroResultadoTC" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Proyecto (EL y TC)</h4>
            </div>
            <div class="modal-body">
                <h4>Formulario para el registro de resultados:</h4>
                <?php include_once('formularioRegistroResultadoTC.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>