
<div class="modal fade" id="ventanaRegistroDetalleEnsayo" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Registro de ensayo (Ensayo de laboratorio)</h4>
            </div>
            <div class="modal-body">
                <h4>Seleccione un proyecto y un tipo de ensayo:</h4>
                <?php include_once('formularioRegistroDetalleEnsayo.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaRegistroMuestra" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Registro de muestra (Ensayo de laboratorio)</h4>
            </div>
            <div class="modal-body">
                <h4>Seleccione un proyecto:</h4>
                <?php include_once('formularioRegistroMuestraEL.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaVerDetalleEnsayo" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Ver detalle de ensayos (Ensayo de laboratorio)</h4>
            </div>
            <div class="modal-body">
                <h4>Lista de proyectos de tipo ensayo de laboratorio:</h4>
                <?php include_once('tablaDetalleEnsayoProyectoEL.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaRegistroResultadoEL" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Registro de resultados (Ensayo de laboratorio)</h4>
            </div>
            <div class="modal-body">
                <h4>Seleccione un proyecto:</h4>
                <?php include_once('formularioRegistroResultadoEL.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaRegistroAlcance" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Registro de alcance (Trabajo de campo)</h4>
            </div>
            <div class="modal-body">
                <h4>Seleccione un proyecto</h4>
                <?php include_once('formularioAlcanceTC.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaEditarAlcance" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Editar alcance (Trabajo de campo)</h4>
            </div>
            <div class="modal-body">
                <h4>Seleccione un proyecto para editar:</h4>
                <?php include_once('formularioEditarAlcanceTC.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaVerAlcance" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Ver alcance (Trabajo de campo):</h4>
            </div>
            <div class="modal-body">
                <h4>Seleccione un proyecto:</h4>
                <?php include_once('formularioVerAlcanceTC.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="ventanaRegistroResultadoTC" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Registro de resultados (Trabajo de campo):</h4>
            </div>
            <div class="modal-body">
                <h4>Seleccione un proyecto:</h4>
                <?php include_once('formularioRegistroResultadoTC.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>