
<div class="modal fade" id="ventanaImprimirReporte" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Reporte</h4>
            </div>
            <div class="modal-body">
                <h4>Formulario para imprimir un reporte:</h4>
                <?php include_once('formularioImprimirReporte.phtml'); ?>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>
</div>