<?php
if (isset($_SESSION['idUsuario'])) {
    if ($_SESSION['codRol'] == 2) {
        header('Location: ' . Conexion::ruta() . '?accion=inicioDirector');
    }
    if ($_SESSION['codRol'] == 3) {
        header('Location: ' . Conexion::ruta() . '?accion=inicioContador');
    }
    if ($_SESSION['codRol'] == 4) {
        header('Location: ' . Conexion::ruta() . '?accion=inicioIngeniero');
    }
    if ($_SESSION['codRol'] == 5) {
        header('Location: ' . Conexion::ruta() . '?accion=inicioAuxiliar');
    }
    if ($_SESSION['codRol'] == 6) {
        header('Location: ' . Conexion::ruta() . '?accion=inicioTecnico');
    }
}
?>
