<div class="table-responsive">
    <table class="table">
        <thead>
        <tr class="success">
            <th>Codigo</th>
            <th>Responsable</th>
            <th>Nombre del proyecto</th>
            <th>Tipo de proyecto</th>
        </tr>
        </thead>
        <tbody>
        <?php for ($i = 0; $i < sizeof($listaProyectoEL); $i = $i + 7) {?>
        <form action="" method="post" name="formInformacionProyectoEL<?php echo $listaProyectoEL[$i]; ?>">
            <tr>
                <td>
                    <a class="btn-default" role="button" data-toggle="collapse"
                       href="#collapseEL<?php echo $listaProyectoEL[$i]; ?>" aria-expanded="false" aria-controls="collapseExample">
                        <?php echo $listaProyectoEL[$i + 1]; ?>
                    </a>
                    <div class="collapse" id="collapseEL<?php echo $listaProyectoEL[$i]; ?>">
                        <div class="well">
                            <ins>Nombre del proyecto:</ins> <?php echo $listaProyectoEL[$i + 2]; ?><br>
                            <ins>Ubicacion:</ins> <?php echo $listaProyectoEL[$i + 4]; ?><br>
                            <ins>Tipo de proyecto:</ins> <?php echo $listaProyectoEL[$i + 3]; ?><br>
                            <ins>Responsable:</ins> <?php echo $listaProyectoEL[$i + 5]; ?><br>
                            <ins>Fecha:</ins>
                            <?php
                            $dia = date("d", strtotime($listaProyectoEL[$i + 6]));
                            $mes = date("F", strtotime($listaProyectoEL[$i + 6]));
                            if ($mes == "January") { $mes = "Enero"; }
                            if ($mes == "February") { $mes = "Febrero"; }
                            if ($mes == "March") { $mes = "Marzo"; }
                            if ($mes == "April") { $mes = "Abril"; }
                            if ($mes == "May") { $mes = "Mayo"; }
                            if ($mes == "June") { $mes = "Junio"; }
                            if ($mes == "July") {$mes = "Julio"; }
                            if ($mes == "August") { $mes = "Agosto"; }
                            if ($mes == "September") { $mes = "Septiembre"; }
                            if ($mes == "October") { $mes = "Octubre"; }
                            if ($mes == "November") { $mes = "Noviembre"; }
                            if ($mes == "December") { $mes = "Diciembre"; }
                            $anio = date("Y", strtotime($listaProyectoEL[$i + 6]));
                            ?>
                            <?php echo $dia." de ".$mes.", ".$anio ?>

                            <div align="center">
                                <input type="hidden" name="idSolicitud" value="<?php echo $listaProyectoEL[$i]; ?>" />
                                <input type="hidden" name="grabarVerInformacionProyecto" value="si" />
                                <input type="button" value="Ver informacion completa"  class="btn btn-primary"
                                       onclick="document.formInformacionProyectoEL<?php echo $listaProyectoEL[$i]; ?>.submit();"/>
                            </div>
                        </div>
                    </div>
                </td>
                <td><?php echo $listaProyectoEL[$i + 5]; ?></td>
                <td><?php echo $listaProyectoEL[$i + 2]; ?></td>
                <td><?php echo $listaProyectoEL[$i + 3]; ?></td>
            </tr>
        </form>
        <?php } ?>
        </tbody>
    </table>
</div>