<div class="table-responsive">
    <table class="table">
        <thead>
        <tr class="success">
            <th>Codigo solicitud</th>
            <th>Fecha solicitud</th>
            <th>Responsable</th>
            <th>Nombre proyecto</th>
            <th>Habilitado</th>
            <th>Codigo proyecto</th>
            <th>Alcance creado</th>
            <th>Anticipo cancelado</th>
            <th>Resultado cargado</th>
            <th>Saldo cancelado</th>
            <th>Informe entregado</th>
        </tr>
        </thead>
        <tbody>
        <?php for ($i = 0; $i < sizeof($listaSeguimientoTC); $i = $i + 11) {?>
            <tr>
                <td><?php echo $listaSeguimientoTC[$i + 1]; ?></td>
                <td><?php echo $listaSeguimientoTC[$i + 2]; ?></td>
                <td><?php echo $listaSeguimientoTC[$i + 3]; ?></td>
                <td><?php echo $listaSeguimientoTC[$i + 4]; ?></td>
                <td><?php echo $listaSeguimientoTC[$i + 5]; ?></td>
                <td><?php echo $listaSeguimientoTC[$i + 6]; ?></td>
                <td><?php echo $listaSeguimientoTC[$i + 7]; ?></td>
                <td><?php echo $listaSeguimientoTC[$i + 8]; ?></td>
                <td></td>
                <td><?php echo $listaSeguimientoTC[$i + 9]; ?></td>
                <td><?php echo $listaSeguimientoTC[$i + 10]; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
</div>