<h4>Ultimas:</h4>
<div class="table-responsive">
    <table class="table">
        <thead>
        <tr class="success">
            <th>Actividad</th>
            <th>Fecha</th>
        </tr>
        </thead>
        <tbody>
        <?php for ($i = 0; $i < sizeof($listaBitacoraUltimasDiez); $i = $i + 9) {?>
            <tr align="left">
                <td>
                    <a class="btn-default" role="button" data-toggle="collapse"
                       href="#collapseBitacora<?php echo $listaBitacoraUltimasDiez[$i]; ?>" aria-expanded="false" aria-controls="collapseExample">
                        <?php echo $listaBitacoraUltimasDiez[$i + 2]; ?>
                    </a>
                    <div class="collapse" id="collapseBitacora<?php echo $listaBitacoraUltimasDiez[$i]; ?>">
                        <div class="well">
                            <ins>Nombre del proyecto:</ins> <?php echo $listaBitacoraUltimasDiez[$i + 4]; ?><br>
                            <ins>Ubicacion:</ins> <?php echo $listaBitacoraUltimasDiez[$i + 6]; ?><br>
                            <ins>Tipo de proyecto:</ins> <?php echo $listaBitacoraUltimasDiez[$i + 5]; ?><br>
                            <ins>Responsable:</ins> <?php echo $listaBitacoraUltimasDiez[$i + 7]; ?><br>
                            <ins>Fecha:</ins>
                            <?php
                            $dia = date("d", strtotime($listaBitacoraUltimasDiez[$i + 8]));
                            $mes = date("F", strtotime($listaBitacoraUltimasDiez[$i + 8]));
                            if ($mes == "January") { $mes = "Enero"; }
                            if ($mes == "February") { $mes = "Febrero"; }
                            if ($mes == "March") { $mes = "Marzo"; }
                            if ($mes == "April") { $mes = "Abril"; }
                            if ($mes == "May") { $mes = "Mayo"; }
                            if ($mes == "June") { $mes = "Junio"; }
                            if ($mes == "July") {$mes = "Julio"; }
                            if ($mes == "August") { $mes = "Agosto"; }
                            if ($mes == "September") { $mes = "Septiembre"; }
                            if ($mes == "October") { $mes = "Octubre"; }
                            if ($mes == "November") { $mes = "Noviembre"; }
                            if ($mes == "December") { $mes = "Diciembre"; }
                            $anio = date("Y", strtotime($listaBitacoraUltimasDiez[$i + 8]));
                            ?>
                            <?php echo $dia." de ".$mes.", ".$anio ?>
                        </div>
                    </div>
                </td>
                <td><?php echo $listaBitacoraUltimasDiez[$i + 3]; ?></td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
</div>