
<div class="modal fade" id="ventanaWorkflow" tabindex="-1" role="dialog" aria-labelledby="ModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Workflow del departamento de Geotecnia</h4>
            </div>
            <div class="modal-body">
                <h4>Workflow</h4>
                <a href='<?php echo Conexion::ruta(); ?>?accion=mapaWorkflow'>Ver Workflow</a>
                <br>
                <h4>Seguimiento de ensayos de laboratorio:</h4>
                <?php include_once('tablaWorkflowEnsayoLaboratorio.phtml'); ?>
                <br>
                <h4>Seguimiento de trabajos de campo:</h4>
                <?php include_once('tablaWorkflowTrabajoCampo.phtml'); ?>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

